////
Copyright 2019 Damian Jarek

Distributed under the Boost Software License, Version 1.0.

See accompanying file LICENSE_1_0.txt or copy at
http://www.boost.org/LICENSE_1_0.txt
////

= HTTPS verification, `<boost/certify/rfc2818_verification.hpp>`

[source, c++]
----
class rfc2818_verification
{
public:
    explicit rfc2818_verification(std::string hostname);

    bool operator()(bool preverified,
                           boost::asio::ssl::verify_context& ctx);

    std::string const& hostname() const;
};
----

The `rfc2818_verification` class implements a callback that performs server
authentication during a TLS handshake. Certificate verification is first
performed using CA certificates imported into OpenSSL. If that fails because of
missing CA certificates, the library will utilize platform specific APIs to try
and complete the process. If verification passes and the peer's certificate
chain is authentic, this callback will continue with the verification process,
as specified in https://tools.ietf.org/html/rfc2818[RFC2818].

Example usage:
[source, c++]
----
boost::asio::ssl::stream<boost::asio::tcp::socket> stream{/*...*/};
stream.set_verify_callback(boost::certify::rfc2818_verification{"github.com"});
----

If verification, using the platform-specific API, fails, the handshake operation
will fail with an error indicating that the certificate chain was self-signed.
