sudo: false

language: cpp

addons:
  apt:
    sources: &base_sources
      - ubuntu-toolchain-r-test

matrix:
  include:
    # g++5
    - os: linux
      addons:
        apt:
          packages:
            - g++-5
          sources:
            - *base_sources

      compiler: g++-5
      env:
        - BOOST_TOOLSET=gcc-5
      script: ./b2 cxxstd=11 toolset=$BOOST_TOOLSET libs/certify/tests libs/certify/tools/

    # Default clang++
    - os: linux
      compiler: clang++
      env:
        - BOOST_TOOLSET=clang
      script: ./b2 cxxstd=11 toolset=$BOOST_TOOLSET libs/certify/tests libs/certify/tools/

    # GCC 6.0, Debug + Coverage
#   - os: linux
#     compiler: g++-6
#     env:
#       - BOOST_TOOLSET=gcc
#     addons:
#       apt:
#         packages:
#           - g++-6
#           - lcov
#           - libssl-dev
#         sources:
#           - *base_sources
#     script:
#       - ctest --output-on-failure -VV -S CMakeModules/ci_build.cmake
#       - ./tools/coverage.sh
#       - curl -s https://codecov.io/bash -o codecov && bash ./codecov -X gcov -f build/coverage.info -y ./.codecov.yml


install:
  - cd ..
  - $TRAVIS_BUILD_DIR/tools/get_boost.sh $TRAVIS_BRANCH $TRAVIS_BUILD_DIR
  - cd boost-root
  - ./bootstrap.sh
