sudo: false

language: cpp

addons:
  apt:
    sources: &base_sources
      - ubuntu-toolchain-r-test

env:
  secure: ArhvhRy+jKtJRZPTgXRp9pexszSgyRbkl1N27C6a+admZWfujttZekivsacnuoc4FLOS6oS0Su6bam6ggw0Tsplli7bVUDvOWHu5+Z8yK64I5lRTRPlbJq/2Q5FxSjSL9cpRyzP+yuZTLEwMMn3nf7euho5do7Yq07SDglZ06VnS+t9eRFyQav8yE7tGQhE0uCRqFReE4mxNoj/STNwho9wHqvBjFzIQIzPF2eyxUHBD829fNd5VzJKAoUBvZ16LymHCqfcnZixdN8ugS7QnDr49qlEwdJoyfPWNK+fVmLeGNSBtwsMUYKbxfbdNaLEhZOC9q69jNgAbfboc/vThkUBcAlwOIaXPwp0ZoTXTf2ADDiwO1Iz49TMUOOYqJwHuLkcRDFK7yqrGqpEV6D1R8da6faNsmCO2xOiTNkS59pXujLIskBBkToI8dRBe/i3khtxdWr1ACPn368LhpIt8am/eXOzjaYWH50ifFQtwsV6y1ABVtHL22BuQMUtWiLUft9amGo61M1kDEF8yvJLyE2Ss5xaAYuDgIGjMfvwisN0hX95aMXamgWvFDIEIwSMBdkZPMmJpO8dkX6GAH9XhbCkw9FWe9KwSKsAVnxYxyMsnsF8ZWMrizKc5l495b9xJ/RJdPw5S2iI2utetPa0lNko9skYlNIzNKBwCTjyi5Jk=


matrix:
  include:
    # g++5
    - os: linux
      dist: xenial
      addons:
        apt:
          packages:
            - g++-5
          sources:
            - *base_sources

      compiler: g++-5
      env:
        - BOOST_TOOLSET=gcc-5
      script: ./b2 cxxstd=11 toolset=$BOOST_TOOLSET libs/certify/tests libs/certify/tools/ libs/certify/examples

    # Default clang++
    - os: linux
      dist: xenial
      compiler: clang++
      env:
        - BOOST_TOOLSET=clang
      script: ./b2 cxxstd=11 toolset=$BOOST_TOOLSET libs/certify/tests libs/certify/tools/ libs/certify/examples

    # GCC 6.0, Debug + Coverage
    - os: linux
      dist: xenial
      compiler: g++-6
      env:
        - BOOST_TOOLSET=gcc-6
        - BUILD_DOCS=true
      addons:
        apt:
          packages:
            - g++-6
            - lcov
          sources:
            - *base_sources
      script:
        - ./b2 variant=debug cxxstd=11 toolset=$BOOST_TOOLSET linkflags="-fprofile-arcs" cxxflags="-fprofile-arcs -ftest-coverage" libs/certify/tests libs/certify/tools/ libs/certify/examples
        - ./libs/certify/tools/coverage.sh
        - curl -s https://codecov.io/bash -o codecov && bash ./codecov -X gcov -f bin.v2/coverage.info -y ./.codecov.yml

    # OS X Clang, C++14, Debug
    - os: osx
      compiler: clang++
      before_install:
        - git clone https://github.com/openssl/openssl.git
        - cd openssl
        - export OPENSSL_ROOT=~/openssl-prefix
        - mkdir -p $OPENSSL_ROOT
        - ./config --prefix=$OPENSSL_ROOT
        - make
        - make install > /dev/null
        - cd ..
        - rm -rf openssl
        - cp tools/user-config.jam ~/
        - alias readlink=greadlink
      script:
        - ./b2 variant=debug cxxstd=14 toolset=clang libs/certify/tests libs/certify/tools/ libs/certify/examples

install:
  - cd ..
  - $TRAVIS_BUILD_DIR/tools/get_boost.sh $TRAVIS_BRANCH $TRAVIS_BUILD_DIR
  - cd boost-root
  - ./bootstrap.sh

after_success:
- ./libs/certify/tools/build_docs.sh
