image: Visual Studio 2017

shallow_clone: true
  
configuration:
#  - Debug
  - Release

platform:
#  - x86
  - x64

environment:
  OPENSSL_ROOT: C:\tools\vcpkg\installed\x64-windows

install:
  - vcpkg install openssl --triplet x64-windows
  - ps: cp tools\user-config.jam ~\user-config.jam
  - SET BOOST_BRANCH=develop
  - IF "%APPVEYOR_REPO_BRANCH%" == "master" SET BOOST_BRANCH=master
  - cd ..
  - git clone -b %BOOST_BRANCH% --depth 1 https://github.com/boostorg/boost.git boost-root
  - cd boost-root
  - bash %APPVEYOR_BUILD_FOLDER%\tools\get_boost.sh
  - mkdir libs\certify
  - XCOPY /s /e /q %APPVEYOR_BUILD_FOLDER% libs\certify\
  - CMD /c bootstrap

build: off

test_script:
  - b2 cxxstd=11 address-model=64 libs\certify\tests

cache: c:\tools\vcpkg\installed\