image: Visual Studio 2017

shallow_clone: true

configuration:
  - Debug
  - Release

platform:
  - x86
  - x64

environment:
  APPVEYOR_SAVE_CACHE_ON_ERROR: true

install:
  - ps: $triplet = "$($env:PLATFORM)-windows"
  - ps: $env:OPENSSL_ROOT = "C:\tools\vcpkg\installed\$($triplet)"
  - ps: $configuration = $env:CONFIGURATION.ToLower()
  - ps: vcpkg install openssl --triplet $triplet
  - ps: cp tools\user-config.jam ~\user-config.jam
  - cd ..
  - bash -c '$APPVEYOR_BUILD_FOLDER/tools/get_boost.sh $APPVEYOR_REPO_BRANCH $APPVEYOR_BUILD_FOLDER'
  - ps: cd boost-root
  - ps: ./bootstrap.bat

build: off

test_script:
  - ps: if ($env:PLATFORM -eq "x86") { $addr_model = "32" } else { $addr_model = "64" }
  - ps: .\b2.exe toolset=msvc cxxstd=11 address-model=$addr_model libs\certify\tests
  - ps: .\b2.exe toolset=msvc cxxstd=11 address-model=$addr_model libs\certify\tools
  - git clean -fdx

cache:
  - c:\tools\vcpkg\installed\
  - c:\projects\boost-root
